-- RoomKit schema: tables, row level security, photo storage and device roles.
--
-- Run this once against a fresh Supabase project, either by pasting it into the
-- SQL editor or with `supabase db push`. It is idempotent enough to re-run on a
-- project that already has it.
--
-- Design notes worth knowing before you change anything:
--
--   Item and chore ids are generated by the client (makeId() -> 'item-ab12cd'),
--   so the primary key is (user_id, id) with a text id rather than a uuid.
--   Scoping the key by user means two accounts can never collide on an id.
--
--   Deletes are tombstoned, not removed. A hard DELETE is invisible to the
--   other device: it still holds the row and would push it back on its next
--   sync, which is how deleted items resurrect themselves.
--
--   updated_at is maintained by a trigger, never accepted from the client, so a
--   device with a wrong clock cannot win a conflict it should have lost.
--
--   Laundry and the room layout live in one JSONB row per user because they are
--   always rewritten as a whole. Per-row sync would buy nothing and cost joins.

create extension if not exists "pgcrypto";

/* ── trigger helper ────────────────────────────────────────────────────────
   This lives in `private`, not `public`, on purpose. PostgREST publishes every
   executable function in an exposed schema as /rest/v1/rpc/<name>, and a
   trigger helper has no business being callable over HTTP. Revoking EXECUTE
   instead does not work: PostgreSQL checks that privilege against the role
   running the statement, so revoking it silently stops the trigger firing and
   hands timestamp control back to the client. Placement is the fix. */

create schema if not exists private;
grant usage on schema private to authenticated, anon, service_role;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

grant execute on function private.touch_updated_at() to authenticated, anon, service_role;

/* ── items ────────────────────────────────────────────────────────────── */

create table if not exists public.items (
  user_id         uuid        not null references auth.users(id) on delete cascade,
  id              text        not null,
  name            text        not null default '',
  category        text        not null default 'misc',
  description     text,
  location        text,
  layer           text,
  status          text        not null default 'clean',
  quantity        integer     not null default 1 check (quantity >= 0),
  wear_count      integer     not null default 0 check (wear_count >= 0),
  tags            jsonb       not null default '[]'::jsonb,
  image           text,
  image_meta      jsonb,
  snooze_until    timestamptz,
  last_touched_at timestamptz not null default now(),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz,
  primary key (user_id, id)
);

create index if not exists items_user_updated_idx on public.items (user_id, updated_at desc);

drop trigger if exists items_touch_updated_at on public.items;
create trigger items_touch_updated_at
  before update on public.items
  for each row execute function private.touch_updated_at();

/* ── chores ───────────────────────────────────────────────────────────── */

create table if not exists public.chores (
  user_id       uuid        not null references auth.users(id) on delete cascade,
  id            text        not null,
  title         text        not null default '',
  detail        text,
  interval_days integer     not null default 7 check (interval_days > 0),
  weekday       integer     check (weekday between 0 and 6),
  hard_deadline boolean     not null default false,
  icon          text,
  location      text,
  last_done_at  timestamptz,
  log           jsonb       not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz,
  primary key (user_id, id)
);

create index if not exists chores_user_updated_idx on public.chores (user_id, updated_at desc);

drop trigger if exists chores_touch_updated_at on public.chores;
create trigger chores_touch_updated_at
  before update on public.chores
  for each row execute function private.touch_updated_at();

/* ── laundry and room design, edited as a whole ───────────────────────── */

create table if not exists public.app_state (
  user_id    uuid        primary key references auth.users(id) on delete cascade,
  laundry    jsonb       not null default '{"entries":[],"history":[]}'::jsonb,
  design     jsonb       not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

drop trigger if exists app_state_touch_updated_at on public.app_state;
create trigger app_state_touch_updated_at
  before update on public.app_state
  for each row execute function private.touch_updated_at();

/* ── devices ───────────────────────────────────────────────────────────────
   Sync used to let every device write, so a laptop left open with a dead
   websocket would push its stale copy over edits made on the phone, silently.
   Roles make that impossible rather than unlikely: exactly one device may
   write and the rest have no code path that does. */

create table if not exists public.devices (
  user_id       uuid        not null references auth.users(id) on delete cascade,
  id            text        not null,
  name          text        not null default 'Unnamed device',
  platform      text,
  role          text        not null default 'viewing'
                            check (role in ('saving', 'viewing', 'archiving')),
  last_seen_at  timestamptz not null default now(),
  last_write_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  primary key (user_id, id)
);

drop trigger if exists devices_touch_updated_at on public.devices;
create trigger devices_touch_updated_at
  before update on public.devices
  for each row execute function private.touch_updated_at();

/**
 * Claim the writer role atomically. Demotion has to happen in the same
 * statement as promotion, or two devices racing both read "nobody is saving"
 * and both end up saving, which is the exact state roles exist to prevent.
 * SECURITY INVOKER so RLS still applies and this can only touch your own rows.
 */
create or replace function public.claim_saving_role(device_id text)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.devices
     set role = case
                  when id = device_id     then 'saving'
                  when role = 'archiving' then 'archiving'
                  else 'viewing'
                end
   where user_id = (select auth.uid());
end;
$$;

/* ── row level security ────────────────────────────────────────────────────
   Every policy has the same shape: you only ever see or touch rows whose
   user_id is your own auth.uid(). No policy exposes another user's row under
   any condition, and the client never holds a service role key. */

alter table public.items     enable row level security;
alter table public.chores    enable row level security;
alter table public.app_state enable row level security;
alter table public.devices   enable row level security;

do $$
declare t text;
begin
  foreach t in array array['items', 'chores', 'app_state', 'devices'] loop
    execute format('drop policy if exists %I_select on public.%I', t, t);
    execute format('drop policy if exists %I_insert on public.%I', t, t);
    execute format('drop policy if exists %I_update on public.%I', t, t);
    execute format('drop policy if exists %I_delete on public.%I', t, t);

    execute format(
      'create policy %I_select on public.%I for select to authenticated
         using ((select auth.uid()) = user_id)', t, t);
    execute format(
      'create policy %I_insert on public.%I for insert to authenticated
         with check ((select auth.uid()) = user_id)', t, t);
    execute format(
      'create policy %I_update on public.%I for update to authenticated
         using ((select auth.uid()) = user_id)
         with check ((select auth.uid()) = user_id)', t, t);
    execute format(
      'create policy %I_delete on public.%I for delete to authenticated
         using ((select auth.uid()) = user_id)', t, t);
  end loop;
end $$;

/* ── realtime ─────────────────────────────────────────────────────────────
   Lets the other device hear about a change instead of polling for it. The
   client treats this as an optimisation, never the mechanism: iOS tears the
   socket down when the screen locks, so the app also re-syncs on becoming
   visible and polls while the socket is down. */

do $$
begin
  alter publication supabase_realtime add table public.items;
exception when duplicate_object then null; end $$;
do $$
begin
  alter publication supabase_realtime add table public.chores;
exception when duplicate_object then null; end $$;
do $$
begin
  alter publication supabase_realtime add table public.app_state;
exception when duplicate_object then null; end $$;
do $$
begin
  alter publication supabase_realtime add table public.devices;
exception when duplicate_object then null; end $$;

/* ── photo storage ────────────────────────────────────────────────────────
   Private bucket, so there is no anonymous URL for an object here: reads go
   through a short lived signed URL. Objects are laid out as <user_id>/<file>
   and every policy checks that first path segment, so one account cannot read,
   list, overwrite or delete another's photos even knowing the object name. */

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('item-photos', 'item-photos', false, 12582912,
        array['image/webp', 'image/jpeg', 'image/png', 'image/gif', 'image/avif'])
on conflict (id) do nothing;

drop policy if exists item_photos_select on storage.objects;
drop policy if exists item_photos_insert on storage.objects;
drop policy if exists item_photos_update on storage.objects;
drop policy if exists item_photos_delete on storage.objects;

create policy item_photos_select on storage.objects
  for select to authenticated
  using (bucket_id = 'item-photos'
         and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy item_photos_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'item-photos'
              and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy item_photos_update on storage.objects
  for update to authenticated
  using (bucket_id = 'item-photos'
         and (storage.foldername(name))[1] = (select auth.uid())::text)
  with check (bucket_id = 'item-photos'
              and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy item_photos_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'item-photos'
         and (storage.foldername(name))[1] = (select auth.uid())::text);
